import React, { useState } from 'react';
import { Post } from '../interfaces/post';

const PostCreation: React.FC = () => {
  const [content, setContent] = useState('');

  const handlePost = async () => {
    const newPost: Post = {
      id: 'unique-post-id', // This ID should be generated by the backend.
      userId: 'current-user-id', // This should come from the user's session or authentication context.
      content: content,
      createdAt: new Date(),
    };

    // TODO: Implement the backend call to save the new post
    console.log(newPost);

    setContent(''); // Clear the content after posting
  };

  return (
    <div>
      <textarea
        value={content}
        onChange={(e) => setContent(e.target.value)}
      />
      <button onClick={handlePost}>Post</button>
    </div>
  );
};

export default PostCreation;
